# Generated by Django 5.0.4 on 2024-06-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$$$$', 'Luxurious'), ('$', 'Cheap'), ('$$', 'Reasonable'), ('$$$', 'EXpensive')], max_length=10),
        ),
    ]
