# Generated by Django 5.0.4 on 2024-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='int_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$', 'Cheap'), ('$$$$', 'Luxurious'), ('$$', 'Reasonable'), ('$$$', 'EXpensive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='int_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
