# Generated by Django 5.0.4 on 2024-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0002_alter_business_int_id_alter_business_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$$$$', 'Luxurious'), ('$$$', 'EXpensive'), ('$$', 'Reasonable'), ('$', 'Cheap')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='int_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
