# Generated by Django 5.0.4 on 2024-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0003_alter_business_price_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$', 'Cheap'), ('$$', 'Reasonable'), ('$$$$', 'Luxurious'), ('$$$', 'EXpensive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')]),
        ),
    ]
