# Generated by Django 5.0.4 on 2024-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0004_alter_business_price_alter_business_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$$$$', 'Luxurious'), ('$', 'Cheap'), ('$$', 'Reasonable'), ('$$$', 'Expensive')], max_length=10),
        ),
    ]
