# Generated by Django 5.0.4 on 2024-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmaster', '0005_alter_business_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(choices=[('$', 'Cheap'), ('$$$', 'Expensive'), ('$$$$', 'Luxurious'), ('$$', 'Reasonable')], max_length=10),
        ),
    ]
